### ISSUE TITLE
Broken Neovim :(

### ISSUE THREAD

**Issue by siduck** [hexoctal/st-undercurl#1]
without patch :
![image](https://user-images.githubusercontent.com/59060246/115993654-5d8aa200-a5f1-11eb-8aa6-5ddfc67930f3.png)

with patch :  
![image](https://user-images.githubusercontent.com/59060246/115994561-25855e00-a5f5-11eb-979a-86d23949df92.png)

**Comment by derriche-massinissa** [comment]
This is bad... is there any output when running the patched st?

Does this only happen inside of NeoVim? How about the shell? If so, there is a conflict with another st patch.
If it only happens inside NeoVim, then the conflict is with a plugin.

Try this in the shell for starters:
```shell
print "\033[4:3;58:2:1mCurly\033[0m"
```
And tell me what happens.

**Comment by derriche-massinissa** [comment]
Ok, I was able to reproduce the issue with your build! So the culprit is an st patch!
I'll investigate later and let you know.

**Comment by siduck** [comment]
> This is bad... is there any output when running the patched st?
> 
> Does this only happen inside of NeoVim? How about the shell? If so, there is a conflict with another st patch.
> If it only happens inside NeoVim, then the conflict is with a plugin.
> 
> Try this in the shell for starters:
> 
> ```shell
> print "\033[4:3;58:2:1mCurly\033[0m"
> ```
> 
> And tell me what happens.

![image](https://user-images.githubusercontent.com/59060246/116003552-0cdc6e80-a61c-11eb-85d4-43b5337d367b.png)

**Comment by derriche-massinissa** [comment]
Fixed it! Could you try the new patch?

There was a conflict with [Boxdraw](https://st.suckless.org/patches/boxdraw/), where we both were using the same value for an enum item. It was just 1 line. It should be ok now... I hope...

**Comment by siduck** [comment]
let me try!

**Comment by siduck** [comment]
everything works now , thank you! @hexoctal
